# Generated by Django 3.2.4 on 2022-09-09 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
                ('CPic', models.ImageField(default='', upload_to='static/category/')),
            ],
        ),
        migrations.CreateModel(
            name='maincate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('picture', models.ImageField(null=True, upload_to='static/mcategory/')),
                ('cdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='mcart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=60)),
                ('pid', models.IntegerField()),
                ('cdate', models.DateField()),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='morder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=70)),
                ('pid', models.IntegerField()),
                ('remarks', models.CharField(max_length=20)),
                ('odate', models.DateField()),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='register',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('mobile', models.CharField(max_length=30)),
                ('ppic', models.ImageField(null=True, upload_to='static/profile/')),
                ('passwd', models.CharField(max_length=60)),
                ('address', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='myproduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pprice', models.FloatField()),
                ('dprice', models.FloatField()),
                ('psize', models.CharField(max_length=20)),
                ('pcolor', models.CharField(max_length=20)),
                ('pdes', models.TextField()),
                ('pdel', models.CharField(max_length=60)),
                ('ppic', models.ImageField(default='', upload_to='static/product/')),
                ('pdate', models.DateField()),
                ('mcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.maincate')),
                ('pcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.category')),
            ],
        ),
    ]
